global:
  scrape_interval: 1m
scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
          - '127.0.0.1:9090'
  - job_name: outline-server-main
    static_configs:
      - targets:
          - '127.0.0.1:9091'
  - job_name: outline-server-ss
    static_configs:
      - targets:
          - '127.0.0.1:9092'
